### ISSUE TITLE
Supplier is created for application for an API definition with a consumer

### ISSUE THREAD

**Issue by amrutprabhu** [asyncapi/java-spring-cloud-stream-template#108]
I am creating a simple consumer application that has the following API definition. 

```
asyncapi: 2.0.0
info:
  title: Some backend events
  version: 1.0.0
channels:
  some.transaction.000:
    description: |-
      This contains events related to transactions.
    subscribe:
      operationId: consumeTransactionEvent
      message:
        $ref: '#/components/messages/trasactionEvent'
components:
  messages:
    trasactionEvent:
      name: trasactionEvent
      schemaFormat: 'application/vnd.aai.asyncapi;version=2.0.0'
      contentType: 'application/json'
      payload:
        ref: '#/components/schemas/TransactionEventPayload'
  schemas:
    TransactionEventPayload:
      type: object
      properties:
        transactionId:
          description: Catalog id for the item
          type: string
          format: uuid
```
when using the java spring cloud stream template it creates a project with two problems. 

1. It creates a supplier rather than a consumer in the consumeTransactionEvent.
2. It using AnonymousSchema1 when there is already a schema created and doesn't even use the schema. 

Here is the code it creates:- 
```
@SpringBootApplication
public class Application {

	private static final Logger logger = LoggerFactory.getLogger(Application.class);

	public static void main(String[] args) {
		SpringApplication.run(Application.class);
	}

	@Bean
	public Supplier<AnonymousSchema1> consumeTransactionEvent() {
		// Add business logic here.
		return null;
	}

}

```
```
@JsonInclude(JsonInclude.Include.NON_NULL)
public class TransactionEventPayload {

	public TransactionEventPayload () {
	}
	public TransactionEventPayload (
		String transactionId) {
		this.transactionId = transactionId;
	}


	private String transactionId;

	public String getTransactionId() {
		return transactionId;
	}

	public TransactionEventPayload setTransactionId(String transactionId) {
		this.transactionId = transactionId;
		return this;
	}


	public String toString() {
		return "TransactionEventPayload ["
		+ " transactionId: " + transactionId
		+ " ]";
	}
}
````

These are the only two classes it creates. 

#### Expected behavior

I think for a subscriber, It should create a consumer and not a supplier. 

Thanks a lot in advance for looking into this

**Comment by derberg** [comment]
@amrutprabhu 

Hey, thanks for the interest with AsyncAPI.

- for the confusion about generated code for `subscribe` operation I recommend reading this article https://www.asyncapi.com/blog/publish-subscribe-semantics. Basically `subscribe` means that others can subscribe to a given channel because your app publishes to it.
- for anonymous schema, as far as I remember you need to add $id to your schema to get a nice id, not anonymous

Let me know if this helps

**Comment by amrutprabhu** [comment]
Hey @derberg , 

Thanks for your quick reply. 

Your first point clarifies the `subscribe` operation creating a publisher Since I was generating code from the client's point of view. It was a bit confusing but after reading the blog post. I understood it well... I changed it use the option view=provider and it created a supplier. Thanks for this :) 


Regarding the issue with AnonymousSchema, I tried going through the documentation again here: https://www.asyncapi.com/docs/specifications/2.0.0#schemaObject 
and also saw the json-schema doc from here: https://datatracker.ietf.org/doc/html/draft-handrews-json-schema-01#section-8.2 
and here: http://json-schema.org/understanding-json-schema/basics.html#declaring-a-unique-identifier

And Tried by adding a `$id` or `id` but the output was the same, It didn't change anything in the code. the `AnonymousSchema1` still remains. 

Also adding my thoughts, Since the definition is already creating the `TransactionEventPayload` class, shouldn't it be using that for the supplier as `supplier<TransactionEventPayload>` rather than defining a separate ID?

**Comment by derberg** [comment]
Can you verify the way you were adding $id against this example https://github.com/asyncapi/java-spring-template/issues/131#issuecomment-843058895?

> Also adding my thoughts, Since the definition is already creating the TransactionEventPayload class, shouldn't it be using that for the supplier as supplier<TransactionEventPayload> rather than defining a separate ID?

@damaru-inc what are your thoughts on this one?

**Comment by amrutprabhu** [comment]
Hey @derberg , 

So I compared the yaml definition you gave me, And I saw a mistake in my yaml. 
In the component section, The message was not properly referencing the payload. I had `ref` instead of `$ref` and therefore it was creating the problem. It didn't even require the need to have `$id` defined. 

That my bad. Sorry for that. :( 

Just my thoughts, Since the reference, was not properly defined, Shouldn't it throw an error... Like it e.g If I add an `id` field to the message, it throws an error saying 

```
 "title": "/components/messages/trasactionEvent should NOT have additional properties",
        "location": {
            "jsonPointer": "/components/messages/trasactionEvent/id",
```

**Comment by derberg** [comment]
not really possible to throw an error as { "ref": "#/components/schemas/TransactionEventPayload"} is a valid json schema

**Comment by amrutprabhu** [comment]
I will close this issue, Thanks a lot for the help :)

**Comment by derberg** [comment]
@amrutprabhu no worries, happy to help.
we are also on slack https://www.asyncapi.com/slack-invite/ so feel free to join the community there
