### ISSUE TITLE
Please tag repo with "generator" & "template"

### ISSUE THREAD

**Issue by Mrc0113** [asyncapi/java-spring-cloud-stream-template#11]
Please tag repo with "generator" & "template" like other code gen templates. 

I had a developer that new this repo existed but couldn't find it as he was doing this search: https://github.com/search?q=topic%3Aasyncapi+topic%3Agenerator+topic%3Atemplate&type=Repositories

**Comment by derberg** [comment]
Hi @Mrc0113 
@damaru-inc already asked for it on Slack https://asyncapi.slack.com/archives/CQVJXFNQL/p1585760178005900

Answer was:
```
We will not add those topics as then the template will show up on a list of official templates, and this template is not yet released, we discussed it here https://asyncapi.slack.com/archives/CQVJXFNQL/p1585315953000500 recently.
```

It is mainly related to https://github.com/asyncapi/java-spring-cloud-stream-template/issues/4

**Comment by derberg** [comment]
You are now listed here https://github.com/search?q=topic%3Aasyncapi+topic%3Agenerator+topic%3Atemplate
and use template as `@asyncapi/java-spring-cloud-stream-template`
