### ISSUE TITLE
Kafka broker information is not populated in the properties file

### ISSUE THREAD

**Issue by amrutprabhu** [asyncapi/java-spring-cloud-stream-template#118]
#### Describe the bug
Kakfa broker information is not created in the properties file that gets generated. 

I have added broker information inside the `servers` section, but this information does not get populated in the properties file. 
I tried using the java-spring-template, and it was able to populate the broker information.

here is the api defintion;

```
asyncapi: 2.0.0
info:
  title: Banking backend events
  version: 1.0.0
servers:
  development:
    url: localhost:9092
    protocol: kafka
channels:
  banking.transaction.000:
    description: |-
      This contains events related to transactions.
    publish:
      operationId: consumeTransactionEvent
      message:
        $ref: '#/components/messages/transactionEvent'
      bindings:
        kafka:
          groupId:
            type: string
            enum: [ 'myGroupId' ]
          clientId:
            type: string
            enum: [ 'myClientId' ]
          bindingVersion: '0.1.0'

components:
  messages:
    transactionEvent:
      name: trasactionEvent
      contentType: 'application/json'
      payload:
        $ref: '#/components/schemas/TransactionEventPayload'
  schemas:
    TransactionEventPayload:
      type: object
      properties:
        transactionId:
          description: Transaction Id
          type: string
          format: uuid
        amount:
          type: integer
```

Here the resulting properties file generated from this definition. 

```

spring:
  cloud:
    function:
      definition: consumeTransactionEvent
    stream:
      bindings:
        consumeTransactionEvent-in-0:
          destination: banking.transaction.000
logging:
  level:
    root: info
    org:
      springframework: info

```

**Comment by derberg** [comment]
It should be fixed in [this](https://github.com/asyncapi/java-spring-cloud-stream-template/blob/master/filters/all.js#L110) filter function. Can you provide the expected output structure?

**Comment by amrutprabhu** [comment]
I was expecting an output something like this
```
spring:
  cloud:
    function:
      definition: consumeTransactionEvent
    stream:
      kafka:
        binder:
          brokers: localhost:9092
      bindings:
        consumeTransactionEvent-out-0:
          destination: banking.transaction.000
```
I also have a question here. As the servers section in the definition allow multiple servers, (e.g development, staging, production server information), which one should it populate in the` brokers` property? because the `brokers` property in the application.yml file would allow only one cluster config. [spring document](https://cloud.spring.io/spring-cloud-stream-binder-kafka/spring-cloud-stream-binder-kafka.html#_kafka_binder_properties).

**Comment by derberg** [comment]
there are 2 possibilities:
- AsyncAPI generator provides a [special parameter](https://github.com/asyncapi/generator/blob/master/docs/authoring.md#special-parameters) that this template could support, so you would just in the end run generation with `-p server=production`. Look how Node.js template uses it https://github.com/asyncapi/nodejs-template/blob/master/template/config/common.yml#L37
- the other java template doesn't use this special parameter and solves it somehow differently because of the use case that you can have multiple production Kafka servers. Support for `server` param was not merged in the end https://github.com/asyncapi/java-spring-template/pull/55. So have a look how it is solved there.

**Comment by jarpz** [comment]
Is this available for the ```@asyncapi/java-spring-cloud-stream-template``? Im running the command with that parameter and its fails.

```
ag src/main/resources/asyncapi.yaml @asyncapi/java-spring-cloud-stream-template -o target/generated-sources/asyncapi -p reactive=true -p artifactType=library -p server=local "-p" "javaPackage=com.test.asyncapi"

Something went wrong:
Error: Template parameter "server" has not been defined in the package.json file under generator property. Please make sure it's listed there before you use it in your template.
    at Object.get [as server] (/Users/jrodriguezp/Projects/test-asyncapi/node_modules/@asyncapi/generator/lib/generator.js:136:19)
    at module.exports.validateTemplateConfig (/Users/jrodriguezp/Projects/test-asyncapi/node_modules/@asyncapi/generator/lib/templateConfigValidator.js:24:59)
    at Generator.generate (/Users/jrodriguezp/Projects/test-asyncapi/node_modules/@asyncapi/generator/lib/generator.js:183:5)
    at /Users/jrodriguezp/Projects/test-asyncapi/node_modules/@asyncapi/generator/cli.js:154:9
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! asyncapi-generator-task@1.0.0 generate: `ag src/main/resources/asyncapi.yaml @asyncapi/java-spring-cloud-stream-template -o target/generated-sources/asyncapi -p reactive=true -p artifactType=library -p server=local "-p" "javaPackage=com.test.asyncapi"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the asyncapi-generator-task@1.0.0 generate script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/jrodriguezp/.npm/_logs/2021-06-16T15_58_20_688Z-debug.log
jrodriguezp@MAD-C02ZJ2E9LVDL test-asyncapi % 

```

**Comment by derberg** [comment]
@jarpz no, I'm just explaining how this can be implemented/done in this template in case @amrutprabhu is interested in contributing it as I know he already contributed some to another java template

**Comment by amrutprabhu** [comment]
Hi @derberg , 

So I read the discussion here: https://github.com/asyncapi/java-spring-template/pull/55 
And It kind of changed my mind about the concept of the server. 

Let me explain. 
How many times would you generate code based on a different environment?

Like e.g
Would you create code with `server= production` separately and code for development separately using `server=development`?
It doesn't make sense to me. 

Instead, it does make sense to have multiple servers for the same environment and in the case of kaka, it means multiple broker info for the same cluster. 

I would also Like to go with the approach of combining all the server information to get to target only one cluster environment.
This also means the example here: https://raw.githubusercontent.com/asyncapi/asyncapi/2.0.0/examples/2.0.0/streetlights.yml would have to change to reflect this. 

What are your thoughts about this?

**Comment by derberg** [comment]
I think it is completely fine, there are just 2 ways to do it, each has its pros and cons, and as you can see even we did not pick the one as the only good one here in asyncapi tools.

there original example should not change now, but it is ok to adopt it here for the development purposes. Just make sure that `server` support is optional and that this template still works without it, so introduce a parameter that will turn on reading of server config or not.

@MichaelDavisSolace any other comments from your side?

**Comment by damaru-inc** [comment]
I'd be happy to add the Kafka support. I'll be back from vacation next week and I'll look at it then.

**Comment by amrutprabhu** [comment]
@derberg 
So we could have a parameter which by default will be off, for reading `server` section. 
And when it's provided, It would read all the entries under the `server` section and concatenate them to a single broker setting for Kafka.

is this how we can solve this?

**Comment by derberg** [comment]
sounds good to me, feel free to upen a PR. Just don't call the param `server` as this param name is reserved. Maybe something like `useServers=true`. Just remember when reading params, this is not boolean, `true` is passed into the generator and template as a string.

**Comment by derberg** [comment]
implemented by @amrutprabhu already
