### ISSUE TITLE
The template does not handle multiple SMF bindings.

### ISSUE THREAD

**Issue by damaru-inc** [asyncapi/java-spring-cloud-stream-template#133]
#### Describe the bug
Documents may contain multiple SMF bindings per operation, but this template does not handle that.

#### How to Reproduce
Run the example below, it causes an error.

#### Expected behaviour
The template should handle this kind of file.

Example:
```
components:
  schemas:
    Person:
      properties:
        name:
          type: string
  messages:
    PersonEvent:
      payload:
        $ref: '#/components/schemas/Person'
      schemaFormat: application/vnd.aai.asyncapi+json;version=2.0.0
      contentType: application/json
channels:
  'person/{eventType}/{eventVerb}':
    publish:
      bindings:
        smf:
          bindingVersion: 0.2.0
          bindings:
            - topicSubscriptions:
                - person/*/updated
              channelType: queue
              queueName: UpdatedHREvents
            - topicSubscriptions:
                - person/*/created
              channelType: queue
              queueName: CreatedHREvents
      message:
        $ref: '#/components/messages/PersonEvent'
    parameters:
      eventVerb:
        schema:
          type: string
      eventType:
        schema:
          type: string
asyncapi: 2.0.0
info:
  title: HRApp
  version: 0.0.1
```

**Comment by damaru-inc** [comment]
Now that the Solace binding is official, the smf one is no longer relevant.

**Comment by derberg** [comment]
@damaru-inc it is not yet "official" in a way that can be used in AsyncAPI, you will have to push it into the spec, just fyi

**Comment by MichaelDavisSolace** [comment]
Good to know! I thought just being in the bindings repo was enough. I'll do a pull request.

**Comment by derberg** [comment]
@damaru-inc no worries, it must be listed in the spec among other bindings and then also added to json schema so it pass the validation. Next release is in January so there is still time
