### ISSUE TITLE
import java.math.BigDecimal instead of using the fully qualified name.

### ISSUE THREAD

**Issue by damaru-inc** [asyncapi/java-spring-cloud-stream-template#141]
#### Reason/Context
Please try answering few of those questions
- Why we need this improvement?
When a schema uses 'number' we use the java.math.BigDecimal class. But instead of importing it, we use the fully qualified name everywhere it's used.
- How will this change help?
This will improve readability.
- What is the motivation? 
We strive to make the code appear as if it were human-written. This looks awkward.

#### Description
Please try answering few of those questions
- What changes have to be introduced?
Will have to detect when we use BigDecimal and adjust the appExtraIncludes function to include it.
- Will this be a breaking change?
no.
- How could it be implemented/designed?
See above.

**Comment by apreshagarwal** [comment]
@derberg Would like to work on this issue

**Comment by derberg** [comment]
@apreshagarwal sorry, I did not notice your comment. You do not have to ask to work on a project. You still interested?

**Comment by apreshagarwal** [comment]
> @apreshagarwal sorry, I did not notice your comment. You do not have to ask to work on a project. You still interested?

@derberg Yes, I am interested. Will create a PR by tomorrow.
