### ISSUE TITLE
An incorrect function signature was generated

### ISSUE THREAD

**Issue by MichaelDavisSolace** [asyncapi/java-spring-cloud-stream-template#15]
#### Describe the bug
A user ran the template against a file that was missing some types on some properties. The generator created this function signature:

```public Function<CovidTracking_StateCurrentData, CovidTracking_StateCurrentData > calculatePercentages()```

which was wrong. After adding the property types the function was created properly:

```public Function<CovidTracking_StateCurrentData, CovidTracking_StateCurrentTestPercentData> calculatePercentages()```

Here's the document:

[bad-function.txt](https://github.com/asyncapi/java-spring-cloud-stream-template/files/4482084/bad-function.txt)

**Comment by damaru-inc** [comment]
I can't reproduce this.
