### ISSUE TITLE
Generator is failing to add 'import com.fasterxml.jackson.annotation.JsonProperty;' statement

### ISSUE THREAD

**Issue by gvensan** [asyncapi/java-spring-cloud-stream-template#157]
#### Describe the bug
Snippet from the asynapi document:
....
        lat:
          default: 0
          examples:
            - -71.518929
          description: An explanation about the purpose of this instance.
          type: number
          title: The lat schema
          $id: '#/properties/lat'
        long:
          default: 0
          examples:
            - -71.518929
          description: An explanation about the purpose of this instance.
          type: number
          title: The long schema
          $id: '#/properties/long'
....

There is a variable by name 'long' !!

In the generated code - 'long' being a reserved word, it did the right thing of naming the variable as "_long" and added a JsonProperty to be "long", which is fine.

But, what the generator failed to do was to include the "import com.fasterxml.jackson.annotation.JsonProperty;"  statement.

#### How to Reproduce
Just add a variable with name "long" in any valid AsyncAPI document and put it through code generation.

#### Expected behavior
"import com.fasterxml.jackson.annotation.JsonProperty;" should automatically be present in the generated POJO.

**Comment by damaru-inc** [comment]
Can you please provide the complete document, properly formatted, perhaps as an attachment?

**Comment by gvensan** [comment]
Sure. Attaching the document. (uploading as txt file) 
[HVAC.txt](https://github.com/asyncapi/java-spring-cloud-stream-template/files/7081177/HVAC.txt)
