### ISSUE TITLE
Generator is failing to add "@Bean" annotation to java.util.function.Function contract

### ISSUE THREAD

**Issue by gvensan** [asyncapi/java-spring-cloud-stream-template#158]
#### Describe the bug
Codegen failed to put the "@Bean" annotation for the Function construct (corresponding import statement is also missing)

#### How to Reproduce
Snippet from AsyncAPI document:
....
channels:
  'SmartTown/Operations/OperationalAlert/created/v1/{AlertPriority}/{AlertType}':
    subscribe:
      x-scs-function-name: processTemperatureReading
      message:
        $ref: '#/components/messages/OperationalAlert'
    parameters:
      AlertType:
        schema:
          type: string
      AlertPriority:
        schema:
          type: string
  'SmartTown/Operations/temperatureReading/created/v1/{city}/{latitude}/{longitude}':
    publish:
      x-scs-function-name: processTemperatureReading
      message:
        $ref: '#/components/messages/TemperatureReading'
    parameters:
      city:
        schema:
          type: string
      latitude:
        schema:
          type: string
      longitude:
        schema:
          type: string
....

#### Expected behavior
Just need to add the @Bean annotation - otherwise one has to do that manually.

**Comment by damaru-inc** [comment]
Can you please provide the complete document, properly formatted, perhaps as an attachment?

**Comment by gvensan** [comment]
Sure. Attaching the document. (uploading as txt file) 

[HVAC.txt](https://github.com/asyncapi/java-spring-cloud-stream-template/files/7081172/HVAC.txt)
