### ISSUE TITLE
Immediately return expression instead of assigning it to the temporary variable 

### ISSUE THREAD

**Issue by derberg** [asyncapi/java-spring-cloud-stream-template#185]
3 occurances:
 - https://sonarcloud.io/project/issues?id=asyncapi_java-spring-cloud-stream-template&issues=AXh_ZhERofWrf92Y-V6s&open=AXh_ZhERofWrf92Y-V6s
 - https://sonarcloud.io/project/issues?id=asyncapi_java-spring-cloud-stream-template&issues=AXh_ZhERofWrf92Y-V6r&open=AXh_ZhERofWrf92Y-V6r
 - https://sonarcloud.io/project/issues?id=asyncapi_java-spring-cloud-stream-template&issues=AXh_ZhERofWrf92Y-V6q&open=AXh_ZhERofWrf92Y-V6q

Reason:
```
Declaring a variable only to immediately return or throw it is a bad practice.

Some developers argue that the practice improves code readability, because it enables them to explicitly name what is being returned. However, this variable is an internal implementation detail that is not exposed to the callers of the method. The method name should be sufficient for callers to know exactly what will be returned.

Noncompliant Code Example
function computeDurationInMilliseconds() {
  var duration = (((hours * 60) + minutes) * 60 + seconds ) * 1000 ;
  return duration;
}
Compliant Solution
function computeDurationInMilliseconds() {
  return (((hours * 60) + minutes) * 60 + seconds ) * 1000 ;
}
```

**Comment by inspire99** [comment]
@derberg 👋 

I checked the sonarcloud references, and see that, they have been closed.

![image](https://user-images.githubusercontent.com/18457700/140018622-b11f1d69-796c-44e4-9e60-57870d44a934.png)

Just wanted to check, if this issue is still open ? 
Reason for asking: wanting to contribute.

Thank you

**Comment by derberg** [comment]
@inspire99 hey, I see it was fixed and merged -> https://github.com/asyncapi/java-spring-cloud-stream-template/pull/187/files

some  other issues that are still available are linked here https://docs.google.com/spreadsheets/d/17YYe-ZompcuUACfCGa8Pc3XunFfWRBrNllIBChJ0yWw/edit#gid=0
