### ISSUE TITLE
Generation of array types is not possible anymore

### ISSUE THREAD

**Issue by Zwitscherle** [asyncapi/java-spring-cloud-stream-template#194]
The code generator is failing everytime it has to generate an array type with the error shown below. 
This change was probably introduced with the release 0.11.3, until release version 0.11.2 it worked fine.

![grafik](https://user-images.githubusercontent.com/47972111/136934426-18251f50-85f0-4de2-8641-c29a6182027a.png)

**Comment by dwij2812** [comment]
This issue has resurfaced in the latest versions i.e. 1.13.x, downgrading to 1.12.1 works, can we please check this once?
