### ISSUE TITLE
Generation fails when schemas have an $Id field.

### ISSUE THREAD

**Issue by MichaelDavisSolace** [asyncapi/java-spring-cloud-stream-template#208]
#### Describe the bug
Generation fails when schemas have an $Id field.

#### How to Reproduce
Run the generator with the attached file, see the error messages.

#### Expected behavior
The file is valid and should work (I renamed it to .txt so it could be attached.)
[asyncapi.txt](https://github.com/asyncapi/java-spring-cloud-stream-template/files/7514254/asyncapi.txt)

**Comment by CameronRushton** [comment]
This issue was found again using another asyncapi file. Here is one that is failing
[fixme-$id-not-stripped.txt](https://github.com/asyncapi/java-spring-cloud-stream-template/files/8921369/fixme-.id-not-stripped.txt)

**Comment by CameronRushton** [comment]
[ProcessPayment.txt](https://github.com/asyncapi/java-spring-cloud-stream-template/files/8942378/ProcessPayment.txt)
Here is another asyncapi document that is reported as failing.
