### ISSUE TITLE
Sample code incomplete

### ISSUE THREAD

**Issue by soutchilin** [asyncapi/java-spring-cloud-stream-template#226]
In the section "Fill in the Business Logic" of [step 10 of the lab](https://codelabs.solace.dev/codelabs/design-document-discover-develop-event-driven-apis/index.html?index=..%2F..index#10) the code doesn't compile because of missed import statements:

> import java.util.function.Function;
import java.util.UUID;
import org.apache.commons.lang3.RandomUtils;
import java.time.*;

And then, there are a conversion from string to int missing in the code, like Interger.parseInt.

**Comment by CameronRushton** [comment]
Tested with the latest version (0.13.3) and couldn't reproduce. Please confirm and provide more detail if this is still an issue. I'll close this issue if it becomes stale again.
