### ISSUE TITLE
Error generating code

### ISSUE THREAD

**Issue by jarpz** [asyncapi/java-spring-cloud-stream-template#27]
#### Describe the bug
I use the following asyncapi.yaml and got and incomprehensible error.

```
asyncapi: '2.0.0'
id: 'urn:com:kafka:server'
info:
  title: Kafka Application
  version: '1.0.0'
  description: Kafka Application
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0
servers:
  production:
    url: localhost:9092
    description: Development server
    protocol: kafka
    protocolVersion: '1.0.0'
    x-trigger-version: v0.9.1-0.20190603184501-d845e1d612f8
    x-activity-version: v0.9.1-0.20190603184501-d845e1d612f8
channels:
  /message:
    description: A message channel
    subscribe:
      summary: Get messages
      message:
        $ref: '#/components/messages/message'
      traits:
        - bindings:
            flogo-kafka:
              partitions: "0"
              offset: 0
    publish:
      summary: Send messages
      message:
        $ref: '#/components/messages/message'
      traits:
        - bindings:
            flogo-kafka:
              partitions: "0"
              offset: 0
  /dup:
    description: A duplicate message channel
    subscribe:
      summary: Get messages
      message:
        $ref: '#/components/messages/message'
    publish:
      summary: Send messages
      message:
        $ref: '#/components/messages/message'
components:
  messages:
    message:
      name: message
      title: A message
      summary: A message
      contentType: application/json
      payload:
        $ref: "#/components/schemas/message"
  schemas:
    message:
      type: object
```

#### How to Reproduce
ag asyncapi.yaml @asyncapi/java-spring-cloud-stream-template --force-write

#### Expected behavior
``` 
Something went wrong:
Error: There was a problem registering the hooks: Cannot find module '../lib/ScsLib'
Require stack:
- /home/jarp/.nvm/versions/node/v14.2.0/lib/node_modules/@asyncapi/generator/node_modules/@asyncapi/java-spring-cloud-stream-template/hooks/post-process.js
- /home/jarp/.nvm/versions/node/v14.2.0/lib/node_modules/@asyncapi/generator/lib/generator.js
- /home/jarp/.nvm/versions/node/v14.2.0/lib/node_modules/@asyncapi/generator/cli.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1020:15)
    at Function.Module._load (internal/modules/cjs/loader.js:890:27)
    at Module.require (internal/modules/cjs/loader.js:1080:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/home/jarp/.nvm/versions/node/v14.2.0/lib/node_modules/@asyncapi/generator/node_modules/@asyncapi/java-spring-cloud-stream-template/hooks/post-process.js:5:16)
    at Module._compile (internal/modules/cjs/loader.js:1176:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1196:10)
    at Module.load (internal/modules/cjs/loader.js:1040:32)
    at Function.Module._load (internal/modules/cjs/loader.js:929:14)
    at Module.require (internal/modules/cjs/loader.js:1080:19)

```

Any suggestion? is this template available for use?

Regards

**Comment by damaru-inc** [comment]
Thanks for reporting this. It's my bug and I'll look at it first thing tomorrow.

**Comment by damaru-inc** [comment]
Hey @jarpz can you please try it again?

**Comment by jarpz** [comment]
> Hey @jarpz can you please try it again?

It happened... 

Based on the contract, the object Message is generated with 2 default constructors:

```
@JsonInclude(JsonInclude.Include.NON_NULL)
public class Message {

	public Message () {
	}
	public Message () { // <-- duplicated constructor
	}



	public String toString() {
		return "Message ["
		+ " ]";
	}
}
```

Also when you config a default application.yml 
``
 messageSupplier-out-0:
          destination: /message # <-- '/' is not allowed by spring-cloud-streams in destinations
        messageConsumer-in-0:
          destination: /message
        dupSupplier-out-0:
          destination: dup
        dupConsumer-in-0:
          destination: /dup

------

Caused by: java.lang.IllegalArgumentException: Topic name can only have ASCII alphanumerics, '.', '_' and '-', but was: '/message'
```

Regards

**Comment by damaru-inc** [comment]
Thanks again for your feedback! I take it your first problem with the import was fixed, right?

As far as the duplicate constructor goes, you defined the payload schema as an empty object. I create two constructors, one with no args and one with an argument for each property.
I'm not sure what kind of Java class you would expect to get generated for an object with no properties. Even if I detected that case and skipped generating the second constructor, the class would not be of any use.

With regards to the channels starting with a slash, different service providers might have different rules. When I tested this with Solace, I got an error "java.lang.IllegalArgumentException: Topic contains empty level - /sensor/temperature". I don't want to write rules into my template about what should be allowed, because maybe some service providers allow topics starting with a slash.

I'd like to close this issue because it was specifically about the include problem. If you still think there is something else that needs to be fixed, please raise a new issue.

**Comment by damaru-inc** [comment]
Fixed the import problem.
