### ISSUE TITLE
Maven/Gradle plugin will exist?

### ISSUE THREAD

**Issue by jarpz** [asyncapi/java-spring-cloud-stream-template#28]
#### Reason/Context
Hi,

Is there any plan to provide a maven/gradle plugin to generate code based on asyncapi?

#### Description
I know this is an initial stage of project but were wonderful to know if maven/gradle plugin will have native support and not depends on third party generation...

Regards

**Comment by derberg** [comment]
Hey, as input for the discussion I can only share that some time ago I bumped into this project https://github.com/ctron/asyncapi-maven that looks like a good start or at least a place to get inspiration from https://github.com/ctron/asyncapi-maven

**Comment by jarpz** [comment]
> Hey, as input for the discussion I can only share that some time ago I bumped into this project https://github.com/ctron/asyncapi-maven that looks like a good start or at least a place to get inspiration from https://github.com/ctron/asyncapi-maven

mmm. But this project you mention has no commits since 2017..  :(

So, it sounds like they abandoned the project.

**Comment by derberg** [comment]
@jarpz yes, this is why I wrote that it is just a place for inspiration
