### ISSUE TITLE
avro schema don't work with java-spring-cloud-stream-template

### ISSUE THREAD

**Issue by alberto1980** [asyncapi/java-spring-cloud-stream-template#53]
Hi,

I can't generate code with java-spring-cloud-template and avro schema. I got the following error

**Something went wrong:
TypeError: Cannot read property 'schemas' of null
    at generate:after (C:\Users\usuario\AppData\Roaming\npm\node_modules\@asyncapi\generator\node_modules\@asyncapi\java-spring-cloud-stream-template\hooks\post-process.js:76:42)
    at C:\Users\usuario\AppData\Roaming\npm\node_modules\@asyncapi\generator\lib\generator.js:729:20
    at Array.map (<anonymous>)
    at Generator.launchHook (C:\Users\usuario\AppData\Roaming\npm\node_modules\@asyncapi\generator\lib\generator.js:727:43)
    at Generator.generate (C:\Users\usuario\AppData\Roaming\npm\node_modules\@asyncapi\generator\lib\generator.js:188:16)
    at async C:\Users\usuario\AppData\Roaming\npm\node_modules\@asyncapi\generator\cli.js:149:9**

My asyncapi specification contains this:

asyncapi: '2.0.0'
info:
  title: Streetlights API
  version: '1.0.0'
  description: |
    The Smartylighting Streetlights API allows you
    to remotely manage the city lights.
  license:
    name: Apache 2.0
    url: 'https://www.apache.org/licenses/LICENSE-2.0'

servers:
  production:
    url: kafka.bootstrap:{port}
    protocol: kafka
    variables:
      port:
        default: '9092'
        enum:
          - '9092'
          - '9093'

channels:
  event.lighting.measured:
    publish:
      bindings:
        kafka:
          groupId: my-group
      operationId: readLightMeasurement
      message:
        schemaFormat: 'application/vnd.apache.avro;version=1.9.0'
        payload: # The following is an Avro schema in YAML format (JSON format is also supported)
          type: record
          doc: User information
          fields:
            - name: displayName
              type: string
            - name: email
              type: string
            - name: age
              type: int
    subscribe:
      operationId: updateLightMeasurement
      message:
        schemaFormat: 'application/vnd.apache.avro;version=1.9.0'
        payload: # The following is an Avro schema in YAML format (JSON format is also supported)
          type: record
          doc: User information
          fields:
            - name: displayName
              type: string
            - name: email
              type: string
            - name: age
              type: int

I have used   1.0.0-rc.7 generator version

Note : I thought that my asyncapi specifications is wrong but when I made the test with the same asyncapi specification and java-spring-template I don't get errors

**Comment by alberto1980** [comment]
Attach the asyncapi specification in a yaml file

**Comment by alberto1980** [comment]
[asyncapi_kafka_avro.zip](https://github.com/asyncapi/java-spring-cloud-stream-template/files/5047056/asyncapi_kafka_avro.zip)

**Comment by derberg** [comment]
@damaru-inc is this template assumption that schemas are only in `components.schemas` ?
I see something like https://github.com/asyncapi/java-spring-cloud-stream-template/blob/f3b3a1d8d87e9b18392267b44e9632ef21a1609b/hooks/post-process.js#L76, did you try `asyncapi.allSchemas()`?

**Comment by alberto1980** [comment]
Hi guys,

Could you tell me what is the current status of the template?
Was the template updated to be able to work with avro schema, either internally or from an external schema?
I just did a series of tests and in all of them I got errors?

thanks

**Comment by derberg** [comment]
@damaru-inc hey man, what is your take on this one?

**Comment by MichaelDavisSolace** [comment]
I hope to get back to working on this in a week or two, I'm in the middle of a crunch right now.

**Comment by damaru-inc** [comment]
Solace has scheduled time for me to look at this. I'll get to it next week.
