### ISSUE TITLE
Generated project does not compile

### ISSUE THREAD

**Issue by gerardbosch** [asyncapi/java-spring-cloud-stream-template#58]
Hi! First of all thanks for working on developing a tooling around AsyncAPI 😃 

I'm facing 2 bugs with the generator.

#### Describe the bug

When using the example reference AsyncAPI definition (https://bit.ly/asyncapi) which is using `camelCase` for schemas, the generated project is not Java compliant and hence does not build.

I observe 2 problems:

##### First one: Casing mismatch (breaks build)

The generated model classes (the schemas) are in a file named in `camelCase.java` whilst the class definition itself is in `PascalCase`.
The above example results in:
  * File name: `dimLightPayload.java`
  * Class definition: `public class DimLightPayload`

So the file name should be always switched to `PascalCase` as its being done with the class name itself (following Java conventions).

One should argue that the definition of the official sample API could be updated to turn schema names into PascalCase to help align conventions. In my personal guideline I always define **schemas** in `PascalCase` and **parameters** in `camelCase`, which semantically maps to classes (or data models) and arguments of a function respectively (I guess in Java and probably many other languages). What do you think @fmvilas ?

But giving the above thought aside, the Java/Spring-Cloud-Stream generator should handle the casing properly 😁  

##### Second one: Duplicate constructor (breaks build)

The generated model class `SentAt`, which is defined in API definition as a `date-time`:

```yaml
    sentAt:
      type: string
      format: date-time
      description: Date and time when the message was sent.
```

contains 2 empty constructors, which prevents the code to compile:

```java
	public SentAt () {
	}
	public SentAt () {
	}
```

Another thing here is that OpenAPI generator for Java, would use a `java.time.LocalDateTime` for this type (instead of generating a model) as defined `date-time` which bould be much more convenient. I know this is an improvement of the current generator template and could be a feature-request instead 😉 

#### How to Reproduce

```shell
npm install -g @asyncapi/generator
ag https://bit.ly/asyncapi @asyncapi/java-spring-cloud-stream-template
mvn clean verify
```

#### Expected behavior

Let the code to compile (and hopefully use a `LocalDate`/`LocalDateTime` for `string/date`/`string/date-time` in YAML 😄 )

**Comment by fmvilas** [comment]
Hey @gerardbosch! Thanks for opening this issue 🙌 I agree it should be fixed. Regarding if it should be changed on the AsyncAPI file or in this code generator, I prefer the latter. The reason is that AsyncAPI files must be programming-language agnostic. The same file may be used by different teams to generate different code in different languages. So yeah, I'd go for this specific template (Spring Cloud Stream) to handle this using the Java conventions.

**Comment by gerardbosch** [comment]
Thanks for answering :) I totally agree that the template must handle the casing conventions properly. Just wanted to point if is there any guidelines for casing in the AsyncAPI spec (I mean guidelines, not enforcements :)

The exactly same bug is in the Spring template (other project). I've just opened another issue there. Cheers!

**Comment by fmvilas** [comment]
No guidelines so far. We think this is something people should decide. Luckily, there's [Spectral](https://github.com/stoplightio/spectral) which can help you set an organization-wide guideline if you want.

**Comment by fmvilas** [comment]
Always. I guess @philsturgeon would be happy to guide you through it 😄

**Comment by philsturgeon** [comment]
Hey! Absolutely, happy to help. 

Here's an introduction to the [entire concept](https://apisyouwonthate.com/blog/automated-style-guides-for-rest-graphql-and-grpc) and here's a link to the documentation explaining the [casing function](https://meta.stoplight.io/docs/spectral/docs/reference/functions.md#casing ) so you can automate camelCase for that property.

**Comment by damaru-inc** [comment]
Issue #57 is a feature request for the date-time support. I hope to get to that soon.

**Comment by gerardbosch** [comment]
Working fine with the template v0.6.2, thanks! :)

**Comment by damaru-inc** [comment]
Thanks for letting us know!
