### ISSUE TITLE
Remove duplicated Java reserved word

### ISSUE THREAD

**Issue by derberg** [asyncapi/java-spring-cloud-stream-template#62]
Remove [this](https://github.com/asyncapi/java-spring-cloud-stream-template/blob/master/lib/scsLib.js#L87) line as it is already registered in line nr 85﻿

**Comment by beni0888** [comment]
Hey guys, I was thinking about starting working on this issue, but it is kind of confusing as it seems that there's already a pull request solving it, but it was closed without being merged. 
@derberg Could you please clarify it?
