### ISSUE TITLE
Cleanup errors in filters

### ISSUE THREAD

**Issue by derberg** [asyncapi/java-spring-cloud-stream-template#63]
Remove unnecessary semicolons:
- https://github.com/asyncapi/java-spring-cloud-stream-template/blob/master/filters/all.js#L148
- https://github.com/asyncapi/java-spring-cloud-stream-template/blob/master/filters/all.js#L339

Remove useless asignments, not used variables:
- https://github.com/asyncapi/java-spring-cloud-stream-template/blob/master/filters/all.js#L357
- https://github.com/asyncapi/java-spring-cloud-stream-template/blob/master/filters/all.js#L386
﻿

**Comment by beni0888** [comment]
Hi guys, 
I'm going to start working on this 🚀

**Comment by derberg** [comment]
@beni0888 let's wait 2 days for a response from @RageZBla here https://github.com/RageZBla/java-spring-cloud-stream-template/pull/2. I somehow did not notice this PR, need to see if Olivier want to reopen
