### ISSUE TITLE
Generation of java code for 'allOff' modifier doesn't generates descendant class

### ISSUE THREAD

**Issue by sysadorn** [asyncapi/java-spring-cloud-stream-template#66]
#### Describe the bug
Generation of java code for 'allOff' modifier doesn't generates descendant class as for Inheritance so Composition

#### How to Reproduce
Using configuration in schemas like this produces only ErrorModel class
<pre>
    ErrorModel:
      type: object
      required:
      - message
      - code
      properties:
        message:
          type: string
        code:
          type: integer
          minimum: 100
          maximum: 600
    ExtendedErrorModel:
      allOf:
      - $ref: '#/components/schemas/ErrorModel'
      - type: object
        required:
        - rootCause
        properties:
          rootCause:
            type: string
</pre>
  
#### Expected behavior
Must be generated ErrorModel.java and ExtendedErrorModel.java

**Comment by MatijaMitic** [comment]
The bug still exists. @sysadorn Have you found a workaround for this?

**Comment by derberg** [comment]
@damaru-inc hey, did you have time to look into this one?

**Comment by sysadorn** [comment]
> The bug still exists. @sysadorn Have you found a workaround for this?

I would use openapi-generator-maven-plugin to generate models.

**Comment by derberg** [comment]
@damaru-inc hey, can you have a look please?

**Comment by damaru-inc** [comment]
I'm looking at this now.
