### ISSUE TITLE
Request for a AWS Kinesis Binder

### ISSUE THREAD

**Issue by zaheershaik** [asyncapi/java-spring-cloud-stream-template#91]
#### Reason/Context
- Why we need this improvement?
It'd help to provider AWS Kinesis binder support with reference to [spring-cloud-stream-binder-aws-kinesis](https://github.com/spring-cloud/spring-cloud-stream-binder-aws-kinesis)
- How will this change help?
Helps in generating code templates for AWS Kinesis users like us.
- What is the motivation? 
Reusable code template for AWS Kinesis users.

#### Description
- What changes have to be introduced?
A new binder implementation similar to Kafka.
- Will this be a breaking change?
No
- How could it be implemented/designed?
May be with reference to [spring-cloud-stream-binder-aws-kinesis](https://github.com/spring-cloud/spring-cloud-stream-binder-aws-kinesis)

**Comment by derberg** [comment]
@damaru-inc hey Michael, what are your thoughts?

**Comment by MichaelDavisSolace** [comment]
I support this, I think binders like this are a great way to enable better code generation.

**Comment by derberg** [comment]
@zaheershaik hey, is this something you planned to contribute? this issue is getting stale and I don't think any maintainer here has enough knowledge about AWS Kinesis to work on it on our own.

**Comment by damaru-inc** [comment]
I certainly don't know anything about Kinesis. I think the best way to get this done is to find a company that uses it and get them to sponsor the development.
