### ISSUE TITLE
Simplify Generated Spring Config when parameters are in channel name and using Solace Binder

### ISSUE THREAD

**Issue by Mrc0113** [asyncapi/java-spring-cloud-stream-template#93]
The Solace Spring Cloud Stream binder introduced [this enhancement](https://github.com/SolaceProducts/solace-spring-cloud/issues/3) in v2.0.0 to enhance destination wildcard handling in the binder. This allows us to simplify the generated config when using the Solace binder for a defined channel w/ parameters. Right now the generated app skeleton includes the `destination` and the `queueAdditionalSubscriptions` in this scenario but with the binder's enhancement only the `destination` will be necessary.

**Comment by Mrc0113** [comment]
@damaru-inc, FYI this is the first item I mentioned via slack

**Comment by derberg** [comment]
@damaru-inc @Mrc0113 this one is still valid? if yes please "unstale" or implement 😄

**Comment by Mrc0113** [comment]
"unstale" please, hoping we can get to this soon :)
