### ISSUE TITLE
Allow for Channel Parameters to be available as message headers

### ISSUE THREAD

**Issue by Mrc0113** [asyncapi/java-spring-cloud-stream-template#94]
Spring Cloud Stream / Spring Cloud Function are currently working on defining header mapping capabilities [in this issue](https://github.com/spring-cloud/spring-cloud-function/issues/676). Once available we should consider using this to  allow for the AsyncAPI code generator template to make channel parameters available as headers on inbound messages. 

For example if the generator received an AsyncAPI document containing a channel like the one below, it could (optionally?) generate the configuration for the parameters to be made available as headers on the Spring Message used by the developer. 
 
```
channels:
  'taxinyc/ops/ride/updated/v1/{ride_status}/{driver_id}':
    publish:
      message:
        $ref: '#/components/messages/TaxiStatusUpdate'
    parameters:
      driver_id:
        schema:
          type: string
      ride_status:
        schema:
          type: string
          enum:
            - accepted
            - pickup
            - enroute
            - dropoff
  ```

**Comment by Mrc0113** [comment]
FYI @damaru-inc this is the second item I mentioned via slack :) 
Note this is still in work at the framework level, but I wanted to capture it before I forget.

**Comment by derberg** [comment]
@damaru-inc @Mrc0113 this one is still valid? if yes please "unstale" or implement 😄

**Comment by Mrc0113** [comment]
Thanks @derberg, still valid. The framework release that will support this should be released in the next week and then we will actually be able to implement.

**Comment by damaru-inc** [comment]
I will be working on this feature within a couple of weeks.
