### ISSUE TITLE
Update Default Versions

### ISSUE THREAD

**Issue by Mrc0113** [asyncapi/java-spring-cloud-stream-template#95]
Should update the default versions of generated apps: 
* Use latest Spring Boot 2.4.X release. Since Spring Boot has modified their releases, 2.5 (when released) may deprecate code from 2.4 but won't remove it. By moving to 2.4 this should future proof the generated apps for a bit. 
* While doing that might as well update to latest Spring Cloud + default binder versions

**Comment by derberg** [comment]
@Mrc0113 @damaru-inc hi folks 😄
